export const lightTheme = {
    body: '#FFF',
    text: '#363537',
    background: '#F5F5F5',
    headerBackground: '#FFFFFF',
    headerText: '#363537',
    headerHover: '#007bff',
    buttonBackground: '#007bff',
    buttonText: '#FFFFFF',
    buttonHover: '#0056b3',
    backgroundSecondary: '#f9f9f9',
    titleColor: '#222',
    textSecondary: '#666',
    skillBackground: '#007bff',
    skillText: '#ffffff',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    heroBackground: '#f5f5f5',
    heroTitleColor: '#333',
    heroSubtitleColor: '#666',
    projectsBackground: '#f5f5f5',
    cardBackground: '#ffffff',
    textColor: '#666',
    emphasisColor: '#007bff',
    buttonHoverBackground: '#0056b3',
    contactBackground: '#f9f9f9',
    linkColor: '#007bff',
    linkHoverColor: '#0056b3',
    iconColor: '#333',
    iconHoverColor: '#007bff',

  };
  
  export const darkTheme = {
    body: '#363537',
    text: '#FAFAFA',
    background: '#282828',
    headerBackground: '#1C1C1C',
    headerText: '#FAFAFA',
    headerHover: '#007bff',
    buttonBackground: '#007bff',
    buttonText: '#FFFFFF',
    buttonHover: '#0056b3',
    backgroundSecondary: '#2a2a2a',
    titleColor: '#ffffff',
    textSecondary: '#cccccc',
    skillBackground: '#0056b3',
    skillText: '#ffffff',
    shadowColor: 'rgba(255, 255, 255, 0.1)',
    heroBackground: '#1a1a1a',
    heroTitleColor: '#ffffff',
    heroSubtitleColor: '#cccccc',
    projectsBackground: '#1a1a1a',
    cardBackground: '#2a2a2a',
    textColor: '#cccccc',
    emphasisColor: '#4da6ff',
    buttonHoverBackground: '#005fa3',
    contactBackground: '#1a1a1a',
    linkColor: '#4da6ff',
    linkHoverColor: '#7fbfff',
    iconColor: '#cccccc',
    iconHoverColor: '#4da6ff',

  };